### ISSUE TITLE
warnungen mit js-controller

### ISSUE THREAD

**Issue by liv-in-sky** [iobroker-community-adapters/ioBroker.plex#114]
habe js-controller und admin 5 upgedatet - habe jetzt warnungen  - kannst du damit etwas anfangen

`
<html><body>

plex.0 | 2021-08-08 19:24:01.812 | warn | Object of state "plex.0.statistics.libraries.1-serien.00-all_time" is missing the required property "common.type"
-- | -- | -- | --
plex.0 | 2021-08-08 19:24:01.811 | warn | Object of state "plex.0.statistics.libraries.1-serien.03-last_30d" is missing the required property "common.type"
plex.0 | 2021-08-08 19:24:01.811 | warn | Object of state "plex.0.statistics.libraries.1-serien.02-last_7d" is missing the required property "common.type"
plex.0 | 2021-08-08 19:24:01.787 | warn | Object of state "plex.0.statistics.libraries.1-serien.01-last_24h" is missing the required property "common.type"
plex.0 | 2021-08-08 19:24:01.787 | warn | Object of state "plex.0.statistics.libraries.1-serien" is missing the required property "common.type"
plex.0 | 2021-08-08 19:24:01.786 | warn | Object of state "plex.0.statistics.libraries" is missing the required property "common.type"
plex.0 | 2021-08-08 19:24:01.786 | warn | Object of state "plex.0.statistics" is missing the required property "common.type"
plex.0 | 2021-08-08 19:24:01.784 | warn | Object of state "plex.0.statistics.libraries.3-schnellladen.00-all_time" is missing the required property "common.type"
plex.0 | 2021-08-08 19:24:01.784 | warn | Object of state "plex.0.statistics.libraries.3-schnellladen.03-last_30d" is missing the required property "common.type"
plex.0 | 2021-08-08 19:24:01.784 | warn | Object of state "plex.0.statistics.libraries.3-schnellladen.02-last_7d" is missing the required property "common.type"
plex.0 | 2021-08-08 19:24:01.783 | warn | Object of state "plex.0.statistics.libraries.3-schnellladen.01-last_24h" is missing the required property "common.type"
plex.0 | 2021-08-08 19:24:01.782 | warn | Object of state "plex.0.statistics.libraries.3-schnellladen" is missing the required property "common.type"
plex.0 | 2021-08-08 19:24:01.782 | warn | Object of state "plex.0.statistics.libraries" is missing the required property "common.type"
plex.0 | 2021-08-08 19:24:01.781 | warn | Object of state "plex.0.statistics" is missing the required property "common.type"
plex.0 | 2021-08-08 19:24:01.781 | warn | Object of state "plex.0.statistics.users.armin@slivinskyde.00-all_time" is missing the required property "common.type"
plex.0 | 2021-08-08 19:24:01.781 | warn | Object of state "plex.0.statistics.users.armin@slivinskyde.03-last_30d" is missing the required property "common.type"
plex.0 | 2021-08-08 19:24:01.780 | warn | Object of state "plex.0.statistics.users.armin@slivinskyde.02-last_7d" is missing the required property "common.type"
plex.0 | 2021-08-08 19:24:01.779 | warn | Object of state "plex.0.statistics.users.armin@slivinskyde.01-last_24h" is missing the required property "common.type"
plex.0 | 2021-08-08 19:24:01.779 | warn | Object of state "plex.0.statistics.users.armin@slivinskyde" is missing the required property "common.type"
plex.0 | 2021-08-08 19:24:01.779 | warn | Object of state "plex.0.statistics.users" is missing the required property "common.type"

</body>
</html>`

**Comment by daes10** [comment]
Habe gleiches bei diversen anderen Datenpunkten.

![grafik](https://user-images.githubusercontent.com/44786122/131261799-a3f71434-1e69-4d75-8676-69fb0ed972af.png)

**Comment by liv-in-sky** [comment]
@daes10 - danke für das posten - versuche @Zefau schon über chat  zu erreichen - der meldet sich leider nicht
ich werde mal noch im forum eine nachricht eingeben

**Comment by daes10** [comment]
Hast du schon was herausgefunden?
Gib doch hier Bescheid, wenn was gemacht wurde bezüglich Admin 5 in dem Adapter.

**Comment by Negalein** [comment]
Problem ist noch immer :(

```
plex.0 2022-01-05 23:15:03.914	warn	Object of state "plex.0.libraries.4-horror" is missing the required property "common.type"
plex.0 2022-01-05 23:15:03.914	warn	Object of state "plex.0.libraries.10-filme" is missing the required property "common.type"
plex.0 2022-01-05 23:15:03.914	warn	Object of state "plex.0.libraries" is missing the required property "common.type"
plex.0 2022-01-05 23:15:03.913	warn	Object of state "plex.0.settings.other" is missing the required property "common.type"
```

**Comment by daes10** [comment]
Ich habe gemerkt, dass seit Admin 5 sich viel getan hat und somit viele Adapter noch nicht korrekt darauf angepasst worden sind. Und daher bei vielen Adapter im Moment diese Probleme noch nicht behoben wurden.

**Comment by Negalein** [comment]
es wäre mal schön, wenn @Zefau sich melden würde!
Aber vermutlich ist dieses Jarvis-Ding ihm wichtiger und der Plex ist zum sterben verurteilt!
Schade!!!!

**Comment by Negalein** [comment]
@Zefau 
Danke für die Info!

**Comment by daes10** [comment]
@Zefau Schade, aber verstehe dich! Gibt immer sehr viel zu tun, dass kann ich mir vorstellen. Vorallem bei mehreren Adapter. Leider bin ich noch bei den Anfängen des Programmierens. Bin aber auf dem Weg Javascript mehr und mehr zu nutzen!
Hoffe dass ich eines Tages auch der Community mehr beitragen kann, Adapter weiter zu entwickeln.

Reine Wissensfrage: @Zefau Bist du beruflich irgendwie als IT/Entwickler tätig oder hast du dir selber alles beigebracht?

(sry frage passt hier nicht rein ich weiss)
Musst hier auch nicht antworten wenn dir das zu persönlich ist. Hätte mich einfach Wunder genommen. evtl. hab ich ja dann Anreiz auch soweit zu kommen ;)

**Comment by Zefau** [comment]
Ich bin im IT Bereich, aber nicht in der Entwicklung. Habe in meiner Schul- und Studienzeit nebenbei PHP programmiert und seit 5 Jahren (als ich mit ioBroker anfing) dann Javascript. Alles nur Hobby :-)

**Comment by liv-in-sky** [comment]
@Zefau  es wäre aber schon nicht schlecht, den adapter für die neue js-controller version zu hinterlassen - ich brauche keine änderungen oder neue features - ist das wirklich ein so großer aufwand ?

**Comment by ticaki** [comment]
Weiß nicht, ob es der beste Weg ist, aber habs für mich gefixt, wenn da andere auch kein Problem  mit haben könnte ich ne PR machen:

https://github.com/ticaki/ioBroker.plex

**Comment by mcm1957** [comment]
@ticaki 

As there is currently no one having time to implement and the possibility to test change a PR would be welcome. I can provide support to merge and perform all necessery step to create a ne release, but I do not have a plex environment to test anything.

So if you can proviede a PR and you are  available at forum for questions arising for the new release I will take a look at it and come back to you. Please do not hesitate to ping me if I do not react app 1 or 2 weeks after a PR release. Thgis qwoudl indicate that I lost the mail ...

You do not need any adaption related to version numberimng. This will be done by the release procedur anyway. But please add a short note about the changes to README.md

**Comment by mcm1957** [comment]
Sorry,
War so im englischen drinnen - falls du eine deutsche Antwort bevorzugst, lass es mich wissen

**Comment by ticaki** [comment]
Passt solange ich nicht englisch antworten muß ist alles gut. :)

**Comment by mcm1957** [comment]
Kein Problem.
Und Forum wär auch 100% deutsch :-)

**Comment by liv-in-sky** [comment]
> @ticaki
> 
> As there is currently no one having time to implement and the possibility to test change a PR would be welcome. I can provide support to merge and perform all necessery step to create a ne release, but I do not have a plex environment to test anything.
> 
> So if you can proviede a PR and you are available at forum for questions arising for the new release I will take a look at it and come back to you. Please do not hesitate to ping me if I do not react app 1 or 2 weeks after a PR release. Thgis qwoudl indicate that I lost the mail ...
> 
KLASSE das da mal jemand wieder ws macht - aber um was geht es eigentlich - sind es die warnungen von oben (erster post) ?

**Comment by ticaki** [comment]
Ja es sind die Warnungen, aber das funktioniert leider noch nicht.

**Comment by ticaki** [comment]
https://github.com/iobroker-community-adapters/ioBroker.plex/releases/tag/v1.0.0
