### ISSUE TITLE
Updateanzeige

### ISSUE THREAD

**Issue by Fritzelspitze** [iobroker-community-adapters/ioBroker.plex#117]
Da ich mich nicht ständig in mein PLEX-Interface einlogge sondern nur Medien konsumiere sehe ich Updates erst spät. Da wäre es super, wenn diese im Adapter angezeigt werden damit man z.B. in VIS auf Update hinweisen kann um sich dann zeitnah um das Update zu kümmern. Irgendwas booleanisches zwecks Iconanzeige, wenn Update Verfügbar.

**Comment by ticaki** [comment]
Das ging und geht schon mit Tautulli
