### ISSUE TITLE
Playlist used invalid characters

### ISSUE THREAD

**Issue by sigi2345** [iobroker-community-adapters/ioBroker.plex#184]
Hi,

Playlist used invalid characters:

<html>
<body>
<pre class="markdown-highlight" style="box-sizing: border-box; overflow: auto; font-family: Menlo, Monaco, Consolas, &quot;Courier New&quot;, monospace; font-size: 13px; display: block; padding: 9.5px; margin: 1rem 0px 10px; line-height: 1.42857; word-break: break-all; overflow-wrap: break-word; color: rgb(200, 200, 200); background-color: rgb(39, 43, 48); border: none; border-radius: 4px; max-height: 350px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><code class="hljs css" data-lines="1" style="box-sizing: border-box; font-family: Menlo, Monaco, Consolas, &quot;Courier New&quot;, monospace; font-size: inherit; padding: 0.5em; color: rgb(230, 225, 220); background: rgb(35, 35, 35); border-radius: 0px; white-space: pre; display: inline-block; overflow-x: auto; user-select: all; overflow-wrap: normal; min-width: 100%;">

  | plex Version : 1.0.3
-- | --
  | 2023-08-26 01:22:31.316	warn	Used invalid characters: plex.0.playlists.fresh❤️.itemsCount changed to plex.0.playlists.fresh_.itemsCount
  |  
  | plex.0
  | 2023-08-26 01:22:31.315	warn	Used invalid characters: plex.0.playlists.❤️tracks.itemsCount changed to plex.0.playlists._tracks.itemsCount
  |  
  | plex.0
  | 2023-08-26 01:22:31.309	warn	Used invalid characters: plex.0.playlists.fresh❤️.updatedAt changed to plex.0.playlists.fresh_.updatedAt
  |  
  | plex.0
  | 2023-08-26 01:22:31.309	warn	Used invalid characters: plex.0.playlists.fresh❤️.updatedAtDate changed to plex.0.playlists.fresh_.updatedAtDate
  |  
  | plex.0
  | 2023-08-26 01:22:31.309	warn	Used invalid characters: plex.0.playlists.fresh❤️.addedAt changed to plex.0.playlists.fresh_.addedAt
  |  
  | plex.0
  | 2023-08-26 01:22:31.309	warn	Used invalid characters: plex.0.playlists.fresh❤️.addedAtDate changed to plex.0.playlists.fresh_.addedAtDate
  |  
  | plex.0
  | 2023-08-26 01:22:31.308	warn	Used invalid characters: plex.0.playlists.fresh❤️.leafCount changed to plex.0.playlists.fresh_.leafCount
  |  
  | plex.0
  | 2023-08-26 01:22:31.307	warn	Used invalid characters: plex.0.playlists.fresh❤️.lastViewedAt changed to plex.0.playlists.fresh_.lastViewedAt
  |  
  | plex.0
  | 2023-08-26 01:22:31.306	warn	Used invalid characters: plex.0.playlists.fresh❤️.lastViewedAtDate changed to plex.0.playlists.fresh_.lastViewedAtDate
  |  
  | plex.0
  | 2023-08-26 01:22:31.306	warn	Used invalid characters: plex.0.playlists.fresh❤️.viewCount changed to plex.0.playlists.fresh_.viewCount
  |  
  | plex.0
  | 2023-08-26 01:22:31.306	warn	Used invalid characters: plex.0.playlists.fresh❤️.playlistType changed to plex.0.playlists.fresh_.playlistType
  |  
  | plex.0
  | 2023-08-26 01:22:31.305	warn	Used invalid characters: plex.0.playlists.fresh❤️.smart changed to plex.0.playlists.fresh_.smart
  |  
  | plex.0
  | 2023-08-26 01:22:31.305	warn	Used invalid characters: plex.0.playlists.fresh❤️.summary changed to plex.0.playlists.fresh_.summary
  |  
  | plex.0
  | 2023-08-26 01:22:31.305	warn	Used invalid characters: plex.0.playlists.fresh❤️.title changed to plex.0.playlists.fresh_.title
  |  
  | plex.0
  | 2023-08-26 01:22:31.304	warn	Used invalid characters: plex.0.playlists.fresh❤️.type changed to plex.0.playlists.fresh_.type
  |  
  | plex.0
  | 2023-08-26 01:22:31.304	warn	Used invalid characters: plex.0.playlists.fresh❤️.guid changed to plex.0.playlists.fresh_.guid
  |  
  | plex.0
  | 2023-08-26 01:22:31.304	warn	Used invalid characters: plex.0.playlists.fresh❤️.key changed to plex.0.playlists.fresh_.key
  |  
  | plex.0
  | 2023-08-26 01:22:31.303	warn	Used invalid characters: plex.0.playlists.fresh❤️.ratingKey changed to plex.0.playlists.fresh_.ratingKey
  |  
  | plex.0
  | 2023-08-26 01:22:31.302	warn	Used invalid characters: plex.0.playlists.❤️tracks.updatedAt changed to plex.0.playlists._tracks.updatedAt
  |  
  | plex.0
  | 2023-08-26 01:22:31.301	warn	Used invalid characters: plex.0.playlists.❤️tracks.updatedAtDate changed to plex.0.playlists._tracks.updatedAtDate
  |  
  | plex.0
  | 2023-08-26 01:22:31.300	warn	Used invalid characters: plex.0.playlists.❤️tracks.addedAt changed to plex.0.playlists._tracks.addedAt
  |  
  | plex.0
  | 2023-08-26 01:22:31.300	warn	Used invalid characters: plex.0.playlists.❤️tracks.addedAtDate changed to plex.0.playlists._tracks.addedAtDate
  |  
  | plex.0
  | 2023-08-26 01:22:31.300	warn	Used invalid characters: plex.0.playlists.❤️tracks.leafCount changed to plex.0.playlists._tracks.leafCount
  |  
  | plex.0
  | 2023-08-26 01:22:31.300	warn	Used invalid characters: plex.0.playlists.❤️tracks.lastViewedAt changed to plex.0.playlists._tracks.lastViewedAt
  |  
  | plex.0
  | 2023-08-26 01:22:31.299	warn	Used invalid characters: plex.0.playlists.❤️tracks.lastViewedAtDate changed to plex.0.playlists._tracks.lastViewedAtDate
  |  
  | plex.0
  | 2023-08-26 01:22:31.299	warn	Used invalid characters: plex.0.playlists.❤️tracks.viewCount changed to plex.0.playlists._tracks.viewCount
  |  
  | plex.0
  | 2023-08-26 01:22:31.299	warn	Used invalid characters: plex.0.playlists.❤️tracks.playlistType changed to plex.0.playlists._tracks.playlistType
  |  
  | plex.0
  | 2023-08-26 01:22:31.298	warn	Used invalid characters: plex.0.playlists.❤️tracks.smart changed to plex.0.playlists._tracks.smart
  |  
  | plex.0
  | 2023-08-26 01:22:31.298	warn	Used invalid characters: plex.0.playlists.❤️tracks.summary changed to plex.0.playlists._tracks.summary
  |  
  | plex.0
  | 2023-08-26 01:22:31.298	warn	Used invalid characters: plex.0.playlists.❤️tracks.title changed to plex.0.playlists._tracks.title
  |  
  | plex.0
  | 2023-08-26 01:22:31.298	warn	Used invalid characters: plex.0.playlists.❤️tracks.type changed to plex.0.playlists._tracks.type
  |  
  | plex.0
  | 2023-08-26 01:22:31.298	warn	Used invalid characters: plex.0.playlists.❤️tracks.guid changed to plex.0.playlists._tracks.guid
  |  
  | plex.0
  | 2023-08-26 01:22:31.297	warn	Used invalid characters: plex.0.playlists.❤️tracks.key changed to plex.0.playlists._tracks.key
  |  
  | plex.0
  | 2023-08-26 01:22:31.297	warn	Used invalid characters: plex.0.playlists.❤️tracks.ratingKey changed to plex.0.playlists._tracks.ratingKey

</code></pre>
</body>
</html>

Forum:

https://forum.iobroker.net/topic/67713/test-adapter-plex-v1-0-x/4?_=1693035993703

System:

Plattform: Windows
RAM: 15.9 GB
Node.js: v18.17.1
NPM: 9.6.7
Admin: 6.9.1

**Comment by mcm1957** [comment]
If needed see snmp adapter routine name2id.
