### ISSUE TITLE
Webhook server did not start at :41891

### ISSUE THREAD

**Issue by gregor-hh** [iobroker-community-adapters/ioBroker.plex#87]
Hello,
I installed the Plex Adapter but it can't receive webhooks from my Plex Server. 
The problem is, that the webookserver is not started.

With:
`netstat -tulep`

I can see that the port is NOT listening. 

Any idea what I can do???

Thank you in advance.

Systeminformation:
`raspberry 4
Node.js = v14.15.4 
NPM =6.14.10`

**Comment by ticaki** [comment]
Das wird wohl nicht mehr aktuell sein.
